name: myafyahub
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  afya_moja_core: ^0.0.55
  app_wrapper: ^0.1.32
  async_redux: ^12.0.0
  cached_network_image: ^3.0.0
  chewie: ^1.2.2
  connectivity_plus: ^2.0.3
  dart_fcm: ^0.0.23
  debug_logger: ^0.0.23
  device_info: ^2.0.2
  domain_objects: ^0.0.31-nullsafety
  double_back_to_close_app: ^2.0.1
  firebase_analytics: ^8.2.0
  firebase_core: ^1.4.0
  firebase_core_platform_interface: ^4.0.1
  firebase_crashlytics: ^2.1.1
  firebase_messaging: ^10.0.8
  firebase_remote_config: ^0.10.0+3
  firebase_remote_config_platform_interface: ^0.3.0+6
  flutter:
    sdk: flutter
  flutter_config: ^2.0.0
  flutter_graphql_client: ^0.1.23
  flutter_html: ^2.0.0
  flutter_image_compress: ^1.0.0
  flutter_localizations:
    sdk: flutter
  flutter_pdfview: ^1.2.1
  flutter_svg: ^0.22.0
  fluttertoast: ^8.0.1-nullsafety.0
  freezed: ^0.14.2
  freezed_annotation: ^0.14.2
  google_fonts: ^2.1.0
  html: ^0.15.0
  http: ^0.13.3
  image_picker: ^0.8.0+1
  intl: ^0.17.0
  json_annotation: ^4.0.1
  json_serializable: ^4.1.3
  just_audio: ^0.9.18
  launch_review: ^3.0.1
  path: ^1.8.0
  path_provider: ^2.0.8
  pin_code_text_field: ^1.8.0
  platform: ^3.0.2
  plugin_platform_interface: ^2.0.2
  quiver: ^3.0.1+1
  rxdart: ^0.27.1
  sentry_flutter: ^5.1.0
  share: ^2.0.4
  shared_preferences: ^2.0.6
  shared_themes: ^0.1.1
  shimmer: ^2.0.0
  sms_autofill: ^2.2.0
  sqflite: ^2.0.0+3
  transparent_image: ^2.0.0
  uni_links: ^0.5.1
  unicons: ^2.0.1
  upgrader: ^3.4.1
  url_launcher: ^6.0.6
  video_player: ^2.2.7

dev_dependencies:
  build_runner: ^2.0.4
  connectivity_plus_platform_interface: ^1.1.1
  device_preview: ^0.7.4
  flutter_gen: ^3.1.1
  flutter_test:
    sdk: flutter
  lint: ^1.3.0
  mockito: ^5.0.7
  mocktail_image_network: ^0.1.0
  pedantic: ^1.11.0
  test: ^1.16.5

flutter:
  fonts:
    - family: Sora
      fonts:
        - asset: fonts/Sora/Sora-Bold.ttf
        - asset: fonts/Sora/Sora-ExtraBold.ttf
        - asset: fonts/Sora/Sora-ExtraLight.ttf
        - asset: fonts/Sora/Sora-Light.ttf
        - asset: fonts/Sora/Sora-Medium.ttf
        - asset: fonts/Sora/Sora-Regular.ttf
        - asset: fonts/Sora/Sora-SemiBold.ttf
        - asset: fonts/Sora/Sora-Thin.ttf
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/
    - packages/afya_moja_core/assets/ken.png
    - packages/afya_moja_core/assets/tza.png
    - packages/afya_moja_core/assets/uga.png
    - packages/afya_moja_core/assets/usa.png
    - packages/afya_moja_core/assets/gbr.png
    - packages/afya_moja_core/assets/bel.png
    - packages/afya_moja_core/assets/nga.png
